version: '2'
services:
  postgres:
    image: postgres:latest
    container_name: book-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=db123
      - POSTGRES_DB=bookdb
    restart: unless-stopped

volumes:
  postgres-data: